shot chance
houghta4/great-lexicon-war pull request #43
Opened 2023-09-22 18:17 UTC by houghta4

WIP formula for enemy shot chance. Will need to see if this fits with the speed of everything else. Right now the only factor in shooting is being on the screen and how far the enemy is from the player

2023-09-27 00:02 UTC, houghta4 commented
I think for just a firing chance that this is good to base it off of distance. Possibly in the future we can have different enemies with different firing rates/ accuracy. eg sniper vs grunt. What do you think of the speed of this?

2023-09-27 01:08 UTC, nnickodem commented
I think its good enough for now, may need to adjust in while building the level but is a pretty simple adjustment

2023-09-27 10:11 UTC, nnickodem requested changes

2023-09-27 10:11 UTC, nnickodem commented on src/game/enemy/systems.rs
> +    let chance = 1.0 / (10.0 * dist); // bigger distance -> lower chance
we will need to make this happen more often, hardly happens at all with this

2023-10-01 23:12 UTC, houghta4 commented
I doubled the chance. I wasn't sure how fast they should be firing since we need to hit an enemy 5 times (plus misses) to kill it. This feels a little better for me with your changes as well. We can keep tweaking if needed

2023-10-01 23:49 UTC, nnickodem approved these changes

2023-10-02 01:11 UTC, merged